# Generated by Django 3.2.3 on 2021-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('either', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='slug',
        ),
        migrations.AddField(
            model_name='favorite',
            name='short_name',
            field=models.CharField(default='unnamed', max_length=50),
        ),
    ]
