# Generated by Django 3.2.3 on 2021-05-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('either', '0002_auto_20210529_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
    ]
