# Generated by Django 3.2.3 on 2021-05-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('either', '0003_auto_20210529_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='short_name',
            field=models.CharField(default='unnamed', max_length=50),
        ),
    ]
