# Generated by Django 3.2.3 on 2021-05-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('either', '0005_auto_20210529_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='short_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Введите название для ссылки'),
        ),
    ]
