# Generated by Django 3.2.3 on 2021-05-29 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('either', '0006_alter_favorite_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
